### ISSUE TITLE
address.setMaxSeg(576) Appears to have been moved to the socket

### ISSUE THREAD

**Issue by flagoworld** [SuitestAutomation/BrightWebSocket#6]
In WebSocketClient.brs, the line:

`address.setMaxSeg(576)`

Should be moved down a few lines and changed to:

`m._socket.setMaxSeg(576)`

**Comment by andriichumak** [comment]
Thanks, @flagoworld, we'll have a look.

@lkrocek could you please check this?

**Comment by cranklin** [comment]
https://github.com/SuitestAutomation/BrightWebSocket/pull/7

**Comment by cranklin** [comment]
Fix: https://github.com/SuitestAutomation/BrightWebSocket/pull/7
